task_manager/labels/urls.py
from django.urls import path

from task_manager.labels import views

app_name = 'labels'

urlpatterns = [
    path('', views.LabelListView.as_view(), name='index'),
    path('create/', views.LabelCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.LabelUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.LabelDeleteView.as_view(), name='delete'),
]

task_manager/statuses/urls.py
from django.urls import path

from task_manager.statuses import views

app_name = 'statuses'

urlpatterns = [
    path('', views.StatusListView.as_view(), name='index'),
    path('create/', views.StatusCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.StatusUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.StatusDeleteView.as_view(), name='delete'),
]

task_manager/tasks/urls.py
from django.urls import path

from task_manager.tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='index'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name='delete'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='detail')
]

task_manager/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.urls import include, path
from django.views.generic import TemplateView

from task_manager.views import CustomLoginView, CustomLogoutView


def trigger_error(request):
    a = None
    a.hello()
    return HttpResponse("Hello, world. You're at the pollapp index.")


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('trigger-error/', trigger_error),
]

task_manager/users/urls.py
from django.urls import path

from task_manager.users import views

app_name = 'users'

urlpatterns = [
    path('', views.UserListView.as_view(), name='index'),
    path('create/', views.UserCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UserUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.UserDeleteView.as_view(), name='delete'),
]

task_manager/labels/models.py
from django.db import models
from django.db.models.deletion import ProtectedError
from django.utils.translation import gettext_lazy as _


class Label(models.Model):
    """Label model for task categorization."""
    name = models.CharField(
        max_length=255,
        blank=False,
        verbose_name=_('Name'),
        unique=True,
        error_messages={
            'unique': _('A label with this name already exists.'),
        }
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def delete(self, *args, **kwargs):
        """Prevents deletion if label is referenced by any tasks."""
        if self.task_set.exists():
            raise ProtectedError(
                _("Cannot delete label in use"),
                self
            )
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Label')
        verbose_name_plural = _('Labels')
        ordering = ['name']

task_manager/statuses/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Status(models.Model):
    """Model representing task status with name uniqueness enforcement."""
    name = models.CharField(
        max_length=255,
        blank=False,
        verbose_name=_('Name'),
        unique=True,
        error_messages={
            'unique': _('A status with this name already exists.'),
        }
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Status')
        verbose_name_plural = _('Statuses')
        ordering = ['name']

task_manager/tasks/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from task_manager.labels.models import Label
from task_manager.statuses.models import Status
from task_manager.users.models import User


class Task(models.Model):
    """Task model representing work items with status, executor and labels."""
    name = models.CharField(
        max_length=255,
        blank=False,
        verbose_name=_('Name'),
        unique=True,
        error_messages={
            'unique': _('Task with this name already exists'),
        }
    )
    description = models.TextField(
        verbose_name=_('Description'),
        blank=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        verbose_name=_('Author'),
        related_name='author',
    )
    status = models.ForeignKey(
        Status,
        on_delete=models.PROTECT,
        verbose_name=_('Status'),
    )
    executor = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        verbose_name=_('Executor'),
        related_name='executor',
        blank=True,
        null=True,
    )
    labels = models.ManyToManyField(
        Label,
        verbose_name=_('Labels'),
        blank=True,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Created at'),
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Task')
        verbose_name_plural = _('Tasks')
        ordering = ['-created_at']

task_manager/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Custom user model with first and last names required."""

    first_name = models.CharField(
        max_length=150,
        blank=False,
        null=False,
        verbose_name=_('First Name'),
    )
    last_name = models.CharField(
        max_length=150,
        blank=False,
        null=False,
        verbose_name=_('Last Name'),
    )

    USERNAME_FIELD = 'username'

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return self.get_full_name()

task_manager/forms.py
from django.contrib.auth.forms import AuthenticationForm


class CustomLoginForm(AuthenticationForm):
    """Authentication form with Bootstrap styling."""
    def __init__(self, *args, **kwargs):
        """Initializes the login form with custom Bootstrap styles."""
        super().__init__(*args, **kwargs)

        bs_cls = 'form-control bg-secondary bg-opacity-50 border-secondary'
        for field in self.fields.values():
            field.widget.attrs['class'] = bs_cls
            field.widget.attrs['placeholder'] = field.label

task_manager/labels/forms.py
from django.forms import ModelForm

from task_manager.labels.models import Label
from task_manager.mixins import FormStyleMixin


class LabelForm(FormStyleMixin, ModelForm):
    """ModelForm for creating and updating Label instances."""
    class Meta:
        model = Label
        fields = ['name']

task_manager/statuses/forms.py
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from task_manager.mixins import FormStyleMixin
from task_manager.statuses.models import Status


class StatusForm(FormStyleMixin, ModelForm):
    """Form for creating and updating Status instances."""
    class Meta:
        model = Status
        fields = ['name']
        labels = {
            'name': _('Name'),
        }

task_manager/tasks/forms.py
from django.forms import ModelForm

from task_manager.mixins import FormStyleMixin
from task_manager.tasks.models import Task


class TaskForm(FormStyleMixin, ModelForm):
    """Form for creating and updating tasks."""
    class Meta:
        model = Task
        fields = ['name', 'description', 'status', 'executor', 'labels']

task_manager/labels/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from task_manager.labels.forms import LabelForm
from task_manager.labels.models import Label
from task_manager.mixins import CustomLoginRequiredMixin, ProtectErrorMixin


class LabelBaseView(CustomLoginRequiredMixin):
    model = Label
    success_url = reverse_lazy("labels:index")


class LabelListView(LabelBaseView, ListView):
    template_name = 'labels/index.html'
    context_object_name = 'labels'
    ordering = ['id']


class LabelFormMixin(SuccessMessageMixin):
    template_name = 'labels/form.html'
    form_class = LabelForm


class LabelCreateView(LabelBaseView, LabelFormMixin, CreateView):
    success_message = _('Label created successfully')
    extra_context = {
        'title': _('Create label'),
        'button_name': _('Create')
    }


class LabelUpdateView(LabelBaseView, LabelFormMixin, UpdateView):
    success_message = _('Label updated successfully')
    extra_context = {
        'title': _('Update label'),
        'button_name': _('Update')
    }


class LabelDeleteView(LabelBaseView, SuccessMessageMixin, 
                      ProtectErrorMixin, DeleteView):
    template_name = 'labels/delete.html'
    success_message = _('Label deleted successfully')
    protected_object_url = reverse_lazy('labels:index')
    protected_object_message = _('Cannot delete label in use')
    extra_context = {
        'title': _('Label deletion'),
        'button_name': _('Yes, delete')
    }

task_manager/statuses/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from task_manager.mixins import CustomLoginRequiredMixin, ProtectErrorMixin
from task_manager.statuses.forms import StatusForm
from task_manager.statuses.models import Status


class StatusBaseView(CustomLoginRequiredMixin):
    """Base view for status operations."""
    model = Status
    success_url = reverse_lazy("statuses:index")


class StatusListView(StatusBaseView, ListView):
    """Display list of all statuses."""
    template_name = 'statuses/index.html'
    context_object_name = 'statuses'
    ordering = ['id']


class StatusCreateView(StatusBaseView, SuccessMessageMixin, CreateView):
    """Create new status."""
    template_name = 'statuses/form.html'
    form_class = StatusForm
    success_message = _('Status was created successfully')
    extra_context = {
        'title': _('Create status'),
        'button_name': _('Create')
    }


class StatusUpdateView(StatusBaseView, SuccessMessageMixin, UpdateView):
    """Update existing status."""
    template_name = 'statuses/form.html'
    form_class = StatusForm
    success_message = _('Status was updated successfully')
    extra_context = {
        'title': _('Update status'),
        'button_name': _('Update')
    }


class StatusDeleteView(StatusBaseView, SuccessMessageMixin, 
                       ProtectErrorMixin, DeleteView):
    """Delete status with protection check."""
    template_name = 'statuses/delete.html'
    success_message = _('Status was deleted successfully')
    protected_object_url = reverse_lazy('statuses:index')
    protected_object_message = _('Cannot delete status in use')
    extra_context = {
        'title': _('Status deletion'),
        'button_name': _('Yes, delete')
    }

task_manager/tasks/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView
from django_filters.views import FilterView

from task_manager.mixins import AuthorPermissionMixin, CustomLoginRequiredMixin
from task_manager.tasks.filters import TaskFilter
from task_manager.tasks.forms import TaskForm
from task_manager.tasks.models import Task


class TaskBaseView(CustomLoginRequiredMixin):
    """Base view for task operations."""
    model = Task
    success_url = reverse_lazy('tasks:index')


class TaskListView(TaskBaseView, FilterView):
    """Display filtered list of tasks."""
    template_name = 'tasks/index.html'
    filterset_class = TaskFilter
    context_object_name = 'tasks'
    ordering = ['id']


class TaskDetailView(TaskBaseView, DetailView):
    """Display task details."""
    template_name = 'tasks/detail.html'
    context_object_name = 'task'


class TaskFormMixin(SuccessMessageMixin):
    """Shared configuration for task forms."""
    template_name = 'tasks/form.html'
    form_class = TaskForm


class TaskCreateView(TaskBaseView, TaskFormMixin, CreateView):
    """Create new task."""
    success_message = _('Task created successfully')
    extra_context = {
        'title': _('Create task'),
        'button_name': _('Create')
    }

    def form_valid(self, form):
        """Set current user as task author."""
        form.instance.author = self.request.user
        return super().form_valid(form)


class TaskUpdateView(TaskBaseView, TaskFormMixin, UpdateView):
    """Update existing task."""
    success_message = _('Task updated successfully')
    extra_context = {
        'title': _('Update task'),
        'button_name': _('Update')
    }


class TaskDeleteView(TaskBaseView, AuthorPermissionMixin, 
                     SuccessMessageMixin, DeleteView):
    """Delete task with author permission check."""
    template_name = 'tasks/delete.html'
    success_message = _('Task deleted successfully')
    permission_denied_url = reverse_lazy('tasks:index')
    permission_denied_message = _("Only the task's author can delete it")
    extra_context = {
        'title': _('Task deletion'),
        'button_name': _('Yes, delete')
    }

task_manager/users/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView,
)

from task_manager.mixins import (
    CustomLoginRequiredMixin,
    ProtectErrorMixin,
    UserPermissionMixin,
)
from task_manager.users.forms import (
    CustomUserChangeForm,
    CustomUserCreationForm,
)
from task_manager.users.models import User

USERS_INDEX_URL = reverse_lazy('users:index')
LOGIN_URL = reverse_lazy('login')
PERMISSION_DENIED_MESSAGE = _("You don't have rights to change another user.")


class UserListView(ListView):
    model = User
    template_name = 'users/index.html'
    context_object_name = 'users'
    ordering = ['id']


class BaseUserView(SuccessMessageMixin):
    """Base class for user views."""
    model = User
    template_name = 'users/form.html'
    context_object_name = 'user'
    permission_denied_url = USERS_INDEX_URL


class UserCreateView(BaseUserView, CreateView):
    class Constants:
        SUCCESS_MESSAGE = _('User was registered successfully')
        TITLE = _('Sign Up')
        BUTTON_NAME = _('Register')

    form_class = CustomUserCreationForm
    success_url = LOGIN_URL
    success_message = Constants.SUCCESS_MESSAGE
    extra_context = {
        'title': Constants.TITLE,
        'button_name': Constants.BUTTON_NAME
    }


class UserUpdateView(CustomLoginRequiredMixin, UserPermissionMixin,
                    BaseUserView, UpdateView):
    form_class = CustomUserChangeForm
    success_url = USERS_INDEX_URL
    success_message = _('User was updated successfully')
    permission_denied_message = PERMISSION_DENIED_MESSAGE
    extra_context = {
        'title': _('Edit profile'),
        'button_name': _('Save changes')
    }


class UserDeleteView(CustomLoginRequiredMixin, UserPermissionMixin,
                    ProtectErrorMixin, BaseUserView, DeleteView):
    template_name = 'users/delete.html'
    success_url = USERS_INDEX_URL
    success_message = _('User was deleted successfully')
    permission_denied_message = PERMISSION_DENIED_MESSAGE
    access_denied_message = PERMISSION_DENIED_MESSAGE
    protected_object_url = USERS_INDEX_URL
    protected_object_message = _('Cannot delete this user '
        'because they are being used')
    extra_context = {
        'title': _('User deletion'),
        'button_name': _('Yes, delete')
    }

task_manager/views.py
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from task_manager.forms import CustomLoginForm


class CustomLoginView(SuccessMessageMixin, LoginView):
    """Custom login view with success message."""
    template_name = 'login_form.html'
    form_class = CustomLoginForm
    next_page = reverse_lazy('index')
    success_message = _('You were logged in')


class CustomLogoutView(SuccessMessageMixin, LogoutView):
    """Custom logout view with info message."""
    next_page = reverse_lazy('index')

    def dispatch(self, request, *args, **kwargs):
        """Adds an info message when user logs out."""
        messages.info(request, _('You were logged out'))
        return super().dispatch(request, *args, **kwargs)

task_manager/templates/statuses/delete.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Statuses" %}{% endblock %}
{% block main_classes %}container py-5{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1>{% trans "Delete status" %}</h1>
    
    <div class="card my-4">
        <div class="card-body">
            <h5 class="card-title">{% trans "Are you sure you want to delete" %} "{{ status.name }}"?</h5>
            
            {% if status.task_set.all %}
                <div class="alert alert-danger mt-3">
                    {% trans "This status is used in tasks and cannot be deleted!" %}
                    <ul class="mt-2">
                        {% for task in status.task_set.all %}
                            <li>{{ task.name }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>
    </div>
    
    <form method="post">
        {% csrf_token %}
        
        {% if not status.task_set.all %}
            <button type="submit" class="btn btn-danger">{% trans "Yes, delete" %}</button>
        {% endif %}
        <a href="{% url 'statuses:list' %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
    </form>
</div>
{% endblock %}

task_manager/templates/statuses/form.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}
{% block main_classes %}container wrapper flex-grow-1{% endblock %}

{% block content %}
<div class="my-4">
  <h1 class="mb-4">{{ title }}</h1>
  
  <form method="post" class="mt-3">
    {% csrf_token %}
    
    {% if form.non_field_errors %}
      <div class="alert alert-danger mb-4">
        {% for error in form.non_field_errors %}
          {{ error }}
        {% endfor %}
      </div>
    {% endif %}
    
    {% for field in form %}
      <div class="mb-3">
        <label for="{{ field.id_for_label }}" class="form-label text-white">
          {{ field.label }}
          {% if field.field.required %}<span class="text-danger">*</span>{% endif %}
        </label>
        
        {{ field }}
        
        {% if field.help_text %}
          <div class="form-text text-white-50 mt-1">
            {{ field.help_text }}
          </div>
        {% endif %}
        
        {% if field.errors %}
          <div class="invalid-feedback d-block text-danger mt-1">
            {{ field.errors|first }}
          </div>
        {% endif %}
      </div>
    {% endfor %}
    
    <div class="mt-4">
      <button type="submit" class="btn btn-outline-success me-2">
        {{ button_name }}
      </button>
      <a href="{% url 'statuses:index' %}" class="btn btn-outline-secondary">
        {% trans 'Cancel' %}
      </a>
    </div>
  </form>
</div>
{% endblock %}

task_manager/templates/statuses/index.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Statuses" %}{% endblock %}
{% block main_classes %}container py-5{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-12 col-lg-10">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1 class="mb-0">{% trans "Statuses" %}</h1>
      <a href="{% url 'statuses:create' %}" class="btn btn-outline-success">
        {% trans "Create status" %}
      </a>
    </div>

    {% if statuses %}
    <div class="table-responsive">
      <table class="table table-dark table-striped table-borderless mb-0">
        <thead>
          <tr>
            <th scope="col" class="w-1">ID</th>
            <th scope="col">{% trans "Name" %}</th>
            <th scope="col" class="text-end w-1">{% trans "Date created" %}</th>
            <th scope="col" class="text-center w-1"></th>
          </tr>
        </thead>
        <tbody>
          {% for status in statuses %}
          <tr>
            <td>{{ status.id }}</td>
            <td>{{ status.name }}</td>
            <td class="text-end">{{ status.created_at|date:"d.m.Y H:i" }}</td>
            <td class="text-center">
              <div class="d-inline-flex flex-wrap justify-content-center gap-2">
                <a href="{% url 'statuses:update' status.id %}" class="btn btn-outline-light">
                  {% trans "Edit" %}
                </a>
                <a href="{% url 'statuses:delete' status.id %}" class="btn btn-outline-danger">
                  {% trans "Delete" %}
                </a>
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% else %}
    <div class="alert alert-info">
      {% trans "No statuses found." %}
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}