task_manager/labels/urls.py
from django.urls import path

from task_manager.labels import views

app_name = 'labels'

urlpatterns = [
    path('', views.LabelListView.as_view(), name='index'),
    path('create/', views.LabelCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.LabelUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.LabelDeleteView.as_view(), name='delete'),
]

task_manager/statuses/urls.py
from django.urls import path

from task_manager.statuses import views

app_name = 'statuses'

urlpatterns = [
    path('', views.StatusListView.as_view(), name='index'),
    path('create/', views.StatusCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.StatusUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.StatusDeleteView.as_view(), name='delete'),
]

task_manager/tasks/urls.py
from django.urls import path

from task_manager.tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='index'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name='delete'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='detail')
]

task_manager/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.urls import include, path
from django.views.generic import TemplateView

from task_manager.views import CustomLoginView, CustomLogoutView


def trigger_error(request):
    a = None
    a.hello()
    return HttpResponse("Hello, world. You're at the pollapp index.")


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('trigger-error/', trigger_error),
]

task_manager/users/urls.py
from django.urls import path

from task_manager.users import views

app_name = 'users'

urlpatterns = [
    path('', views.UserListView.as_view(), name='index'),
    path('create/', views.UserCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UserUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.UserDeleteView.as_view(), name='delete'),
]

task_manager/forms.py
from django.contrib.auth.forms import AuthenticationForm


class CustomLoginForm(AuthenticationForm):
    """Authentication form with Bootstrap styling."""
    def __init__(self, *args, **kwargs):
        """Initializes the login form with custom Bootstrap styles."""
        super().__init__(*args, **kwargs)

        bs_cls = 'form-control bg-secondary bg-opacity-50 border-secondary'
        for field in self.fields.values():
            field.widget.attrs['class'] = bs_cls
            field.widget.attrs['placeholder'] = field.label

task_manager/labels/forms.py
from django.forms import ModelForm

from task_manager.labels.models import Label
from task_manager.mixins import FormStyleMixin


class LabelForm(FormStyleMixin, ModelForm):
    """ModelForm for creating and updating Label instances."""
    class Meta:
        model = Label
        fields = ['name']

task_manager/statuses/forms.py
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from task_manager.mixins import FormStyleMixin
from task_manager.statuses.models import Status


class StatusForm(FormStyleMixin, ModelForm):
    """Form for creating and updating Status instances."""
    class Meta:
        model = Status
        fields = ['name']
        labels = {
            'name': _('Name'),
        }

task_manager/tasks/forms.py
from django.forms import ModelForm

from task_manager.mixins import FormStyleMixin
from task_manager.tasks.models import Task


class TaskForm(FormStyleMixin, ModelForm):
    """Form for creating and updating tasks."""
    class Meta:
        model = Task
        fields = ['name', 'description', 'status', 'executor', 'labels']

task_manager/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _

from task_manager.mixins import FormStyleMixin
from task_manager.users.models import User

MIN_PASSWORD_LENGTH = 3


class BaseUserForm:
    """Base configuration for user forms."""
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username')
        help_texts = {
            'username': _(
                'Required. 150 characters or fewer. '
                'Letters, digits and @/./+/-/_ only.'
            ),
        }


class CustomUserCreationForm(FormStyleMixin, UserCreationForm):
    """User registration form with enhanced validation."""
    class Meta(BaseUserForm.Meta):
        fields = (*BaseUserForm.Meta.fields, 'password1', 'password2')
        help_texts = {
            **BaseUserForm.Meta.help_texts,
            'password1': _(
                f"Your password must contain at least "
                f"{MIN_PASSWORD_LENGTH} characters."
            ),
            'password2': _('Please enter your password again to confirm.'),
        }

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2:
            if password1 != password2:
                self.add_error("password2", _("Passwords don't match."))
            elif len(password1) < MIN_PASSWORD_LENGTH:
                self.add_error(
                    "password2",
                    _("Password must contain " 
                    "at least %(min_length)d characters.") % {
                        'min_length': MIN_PASSWORD_LENGTH
                    }
                )
        return cleaned_data


class CustomUserChangeForm(FormStyleMixin, forms.ModelForm):
    """User edit form with password change support."""
    password1 = forms.CharField(
        label=_("New Password"),
        widget=forms.PasswordInput,
        required=True,
        help_text=_(
            f"Minimum {MIN_PASSWORD_LENGTH} characters."
        ),
    )
    password2 = forms.CharField(
        label=_("Confirm Password"),
        widget=forms.PasswordInput,
        required=True,
        help_text=_("Enter the same password for verification."),
    )

    class Meta(BaseUserForm.Meta):
        fields = (*BaseUserForm.Meta.fields, 'password1', 'password2')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'password' in self.fields:
            del self.fields['password']

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 or password2:
            if password1 != password2:
                self.add_error("password2", _("Passwords don't match."))
            elif len(password1) < MIN_PASSWORD_LENGTH:
                self.add_error(
                    "password2",
                    _("Password must contain "
                    "at least %(min_length)d characters.") % {
                        'min_length': MIN_PASSWORD_LENGTH
                    }
                )
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        if new_password := self.cleaned_data.get("password1"):
            user.set_password(new_password)
        if commit:
            user.save()
        return user

task_manager/labels/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from task_manager.labels.forms import LabelForm
from task_manager.labels.models import Label
from task_manager.mixins import CustomLoginRequiredMixin, ProtectErrorMixin


class LabelBaseView(CustomLoginRequiredMixin):
    model = Label
    success_url = reverse_lazy("labels:index")


class LabelListView(LabelBaseView, ListView):
    template_name = 'labels/index.html'
    context_object_name = 'labels'
    ordering = ['id']


class LabelFormMixin(SuccessMessageMixin):
    template_name = 'labels/form.html'
    form_class = LabelForm


class LabelCreateView(LabelBaseView, LabelFormMixin, CreateView):
    success_message = _('Label created successfully')
    extra_context = {
        'title': _('Create label'),
        'button_name': _('Create')
    }


class LabelUpdateView(LabelBaseView, LabelFormMixin, UpdateView):
    success_message = _('Label updated successfully')
    extra_context = {
        'title': _('Update label'),
        'button_name': _('Update')
    }


class LabelDeleteView(LabelBaseView, SuccessMessageMixin, 
                      ProtectErrorMixin, DeleteView):
    template_name = 'labels/delete.html'
    success_message = _('Label deleted successfully')
    protected_object_url = reverse_lazy('labels:index')
    protected_object_message = _('Cannot delete label in use')
    extra_context = {
        'title': _('Label deletion'),
        'button_name': _('Yes, delete')
    }

task_manager/statuses/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from task_manager.mixins import CustomLoginRequiredMixin, ProtectErrorMixin
from task_manager.statuses.forms import StatusForm
from task_manager.statuses.models import Status


class StatusBaseView(CustomLoginRequiredMixin):
    """Base view for status operations."""
    model = Status
    success_url = reverse_lazy("statuses:index")


class StatusListView(StatusBaseView, ListView):
    """Display list of all statuses."""
    template_name = 'statuses/index.html'
    context_object_name = 'statuses'
    ordering = ['id']


class StatusCreateView(StatusBaseView, SuccessMessageMixin, CreateView):
    """Create new status."""
    template_name = 'statuses/form.html'
    form_class = StatusForm
    success_message = _('Status was created successfully')
    extra_context = {
        'title': _('Create status'),
        'button_name': _('Create')
    }


class StatusUpdateView(StatusBaseView, SuccessMessageMixin, UpdateView):
    """Update existing status."""
    template_name = 'statuses/form.html'
    form_class = StatusForm
    success_message = _('Status was updated successfully')
    extra_context = {
        'title': _('Update status'),
        'button_name': _('Update')
    }


class StatusDeleteView(StatusBaseView, SuccessMessageMixin, 
                       ProtectErrorMixin, DeleteView):
    """Delete status with protection check."""
    template_name = 'statuses/delete.html'
    success_message = _('Status was deleted successfully')
    protected_object_url = reverse_lazy('statuses:index')
    protected_object_message = _('Cannot delete status in use')
    extra_context = {
        'title': _('Status deletion'),
        'button_name': _('Yes, delete')
    }

task_manager/tasks/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView
from django_filters.views import FilterView

from task_manager.mixins import AuthorPermissionMixin, CustomLoginRequiredMixin
from task_manager.tasks.filters import TaskFilter
from task_manager.tasks.forms import TaskForm
from task_manager.tasks.models import Task


class TaskBaseView(CustomLoginRequiredMixin):
    """Base view for task operations."""
    model = Task
    success_url = reverse_lazy('tasks:index')


class TaskListView(TaskBaseView, FilterView):
    """Display filtered list of tasks."""
    template_name = 'tasks/index.html'
    filterset_class = TaskFilter
    context_object_name = 'tasks'
    ordering = ['id']


class TaskDetailView(TaskBaseView, DetailView):
    """Display task details."""
    template_name = 'tasks/detail.html'
    context_object_name = 'task'


class TaskFormMixin(SuccessMessageMixin):
    """Shared configuration for task forms."""
    template_name = 'tasks/form.html'
    form_class = TaskForm


class TaskCreateView(TaskBaseView, TaskFormMixin, CreateView):
    """Create new task."""
    success_message = _('Task created successfully')
    extra_context = {
        'title': _('Create task'),
        'button_name': _('Create')
    }

    def form_valid(self, form):
        """Set current user as task author."""
        form.instance.author = self.request.user
        return super().form_valid(form)


class TaskUpdateView(TaskBaseView, TaskFormMixin, UpdateView):
    """Update existing task."""
    success_message = _('Task updated successfully')
    extra_context = {
        'title': _('Update task'),
        'button_name': _('Update')
    }


class TaskDeleteView(TaskBaseView, AuthorPermissionMixin, 
                     SuccessMessageMixin, DeleteView):
    """Delete task with author permission check."""
    template_name = 'tasks/delete.html'
    success_message = _('Task deleted successfully')
    permission_denied_url = reverse_lazy('tasks:index')
    permission_denied_message = _("Only the task's author can delete it")
    extra_context = {
        'title': _('Task deletion'),
        'button_name': _('Yes, delete')
    }

task_manager/users/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView,
)

from task_manager.mixins import (
    CustomLoginRequiredMixin,
    ProtectErrorMixin,
    UserPermissionMixin,
)
from task_manager.users.forms import (
    CustomUserChangeForm,
    CustomUserCreationForm,
)
from task_manager.users.models import User

USERS_INDEX_URL = reverse_lazy('users:index')
LOGIN_URL = reverse_lazy('login')
PERMISSION_DENIED_MESSAGE = _("You don't have rights to change another user.")


class UserListView(ListView):
    model = User
    template_name = 'users/index.html'
    context_object_name = 'users'
    ordering = ['id']


class BaseUserView(SuccessMessageMixin):
    """Base class for user views."""
    model = User
    template_name = 'users/form.html'
    context_object_name = 'user'
    permission_denied_url = USERS_INDEX_URL


class UserCreateView(BaseUserView, CreateView):
    class Constants:
        SUCCESS_MESSAGE = _('User was registered successfully')
        TITLE = _('Sign Up')
        BUTTON_NAME = _('Register')

    form_class = CustomUserCreationForm
    success_url = LOGIN_URL
    success_message = Constants.SUCCESS_MESSAGE
    extra_context = {
        'title': Constants.TITLE,
        'button_name': Constants.BUTTON_NAME
    }


class UserUpdateView(CustomLoginRequiredMixin, UserPermissionMixin,
                    BaseUserView, UpdateView):
    form_class = CustomUserChangeForm
    success_url = USERS_INDEX_URL
    success_message = _('User was updated successfully')
    permission_denied_message = PERMISSION_DENIED_MESSAGE
    extra_context = {
        'title': _('Edit profile'),
        'button_name': _('Save changes')
    }


class UserDeleteView(CustomLoginRequiredMixin, UserPermissionMixin,
                    ProtectErrorMixin, BaseUserView, DeleteView):
    template_name = 'users/delete.html'
    success_url = USERS_INDEX_URL
    success_message = _('User was deleted successfully')
    permission_denied_message = PERMISSION_DENIED_MESSAGE
    access_denied_message = PERMISSION_DENIED_MESSAGE
    protected_object_url = USERS_INDEX_URL
    protected_object_message = _('Cannot delete this user '
        'because they are being used')
    extra_context = {
        'title': _('User deletion'),
        'button_name': _('Yes, delete')
    }

task_manager/views.py
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from task_manager.forms import CustomLoginForm


class CustomLoginView(SuccessMessageMixin, LoginView):
    """Custom login view with success message."""
    template_name = 'login_form.html'
    form_class = CustomLoginForm
    next_page = reverse_lazy('index')
    success_message = _('You were logged in')


class CustomLogoutView(SuccessMessageMixin, LogoutView):
    """Custom logout view with info message."""
    next_page = reverse_lazy('index')

    def dispatch(self, request, *args, **kwargs):
        """Adds an info message when user logs out."""
        messages.info(request, _('You were logged out'))
        return super().dispatch(request, *args, **kwargs)

task_manager/templates/includes/base_form.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% block form_title %}{% endblock %}{% endblock %}
{% block main_classes %}container py-3{% endblock %}

{% block content %}
<div class="card mx-auto bg-dark bg-opacity-25 border-secondary col-md-6 col-lg-4">
  <div class="card-body p-4">
    <div class="text-center mb-4">
      <h1 class="h3 mb-2 text-light fw-normal">{% block form_heading %}{% endblock %}</h1>
      <hr class="border-secondary w-50 mx-auto">
    </div>

    <form method="post" novalidate class="text-light">
      {% csrf_token %}
      {% if form.non_field_errors %}
        <div class="alert alert-danger">
          {% for error in form.non_field_errors %}
            {{ error }}
          {% endfor %}
        </div>
      {% endif %}

      <div class="row g-2">
        {% for field in form %}
          {% include "includes/form_field.html" %}
        {% endfor %}
      </div>

      {% block extra_fields %}{% endblock %}

      <div class="col-12 mt-4">
        <button class="{% block button_classes %}btn btn-outline-success w-100 py-2{% endblock %}" type="submit">
          {% block form_button %}{% endblock %}
        </button>
      </div>

      {% block bottom_text %}{% endblock %}
    </form>
  </div>
</div>
{% endblock %}

task_manager/templates/includes/footer.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<div class="container d-flex justify-content-end w-100">
  <div class="text-end text-secondary small">
    <p class="mb-0">
      &copy; {% now "Y" %} Task Manager |
      Developed by
      <a href="https://github.com/nyanyapushkina/python-project-52"
         class="link-light text-decoration-none"
         target="_blank" rel="noopener noreferrer">
         Arina Khokhlova
      </a>
    </p>
  </div>
</div>

task_manager/templates/includes/form_field.html
{% load i18n %}

<div class="col-12">
  <label for="{{ field.id_for_label }}" class="form-label">
    {{ field.label }}
  </label>
  {{ field }}
  {% if field.help_text %}
    <div class="form-text text-light text-opacity-50">
      {{ field.help_text|striptags }}
    </div>
  {% endif %}
  {% if field.errors %}
    <div class="invalid-feedback d-block">
      {% for error in field.errors %}
        {{ error }}
      {% endfor %}
    </div>
  {% endif %}
</div>

task_manager/templates/includes/navbar.html
{% load i18n %}

<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <a class="navbar-brand mb-0 h1" href="{% url 'index' %}">{% trans "Task Manager" %}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:index' %}">{% trans "Users" %}</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{% url 'statuses:index' %}">{% trans "Statuses" %}</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'labels:index' %}">{% trans "Labels" %}</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'tasks:index' %}">{% trans "Tasks" %}</a></li>
          <li class="nav-item">
            <form class="me-auto mb-2 mb-md-0" action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <input class="btn nav-link" type="submit" value="{% trans 'Log Out' %}">
            </form>
        </li>
        {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">{% trans "Log In" context "menu_item" %}</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'users:create' %}">{% trans "Sign Up" context "menu_item" %}</a></li>
        {% endif %}
      </ul>
      <form action="{% url 'set_language' %}" method="post" class="d-flex align-items-center ms-auto">
        {% csrf_token %}
        <button type="submit" name="language" value="ru"
                class="btn btn-sm btn-outline-light me-2 {% if LANGUAGE_CODE == 'ru' %}border-white{% endif %}">
          RU
        </button>
        <button type="submit" name="language" value="en"
                class="btn btn-sm btn-outline-light {% if LANGUAGE_CODE == 'en' %}border-white{% endif %}">
          EN
        </button>
      </form>
    </div>
  </div>
</nav>